name: CI

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker-ghcr.yml@0.40.17
    permissions:
      packages: write
  release-semantic:
    needs: build
    name: Semantic Release
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0.40.17
    secrets:
      GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
